name: baato_maps
description: "A Flutter package for Baato Maps. Baato Maps is a powerful and flexible mapping solution for Flutter applications."
version: 2.0.0
homepage: https://github.com/baato/flutter_baato_maps
license: MIT

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl: ^0.25.0
  baato_api:
    path: ../baato-flutter
  path_provider: ^2.1.5
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  assets:
    - lib/assets/markers/
    - lib/assets/map_res/sprites/
    - lib/assets/logo/
